---
--- The **PLAYER** table is the structure used to define a custom player class
--- via [player_manager.RegisterClass](https://wiki.facepunch.com/gmod/player_manager.RegisterClass).
--- Player class methods receive the authoring table as `self`, with the driven
--- [Player](https://wiki.facepunch.com/gmod/Player) entity available as `self.Player`.
---
--- The fields below mirror the shipped `player_default` class
--- (`garrysmod/gamemodes/base/gamemode/player_class/player_default.lua`); the
--- `Player`, `ClassID` and `Func` fields are injected at runtime by
--- `player_manager.lua`'s `LookupPlayerClass`. All fields are optional because a
--- player class only authors the subset it wants to override.
---
---@class PlayerClass
---@field Player Player The Player entity this class instance is driving. Injected at runtime by player_manager. Always present inside class methods.
---@field ClassID? number Network string ID of the active player class. Injected at runtime by player_manager.
---@field Func? fun() Internal no-op placeholder. Injected at runtime by player_manager.
---@field DisplayName? string Human-readable display name for this player class.
---@field SlowWalkSpeed number=200 Movement speed when slow-walking (+WALK).
---@field WalkSpeed number=400 Movement speed when walking (not running).
---@field RunSpeed number=600 Movement speed when running.
---@field CrouchedWalkSpeed number=0.3 Multiplier applied to move speed while crouching.
---@field DuckSpeed number=0.3 Speed of transition from standing to crouching.
---@field UnDuckSpeed number=0.3 Speed of transition from crouching to standing.
---@field JumpPower number=200 Vertical impulse strength on jump.
---@field CanUseFlashlight boolean=true Whether the player can use the flashlight.
---@field MaxHealth number=100 Maximum health the player can have.
---@field MaxArmor number=100 Maximum armor the player can have.
---@field StartHealth number=100 Health given to the player on spawn.
---@field StartArmor number=0 Armor given to the player on spawn.
---@field DropWeaponOnDie boolean=false Whether to drop the active weapon on death.
---@field TeammateNoCollide boolean=true Whether teammates pass through each other.
---@field AvoidPlayers boolean=true Whether the player auto-swerves around others.
---@field UseVMHands boolean=true Whether to use viewmodel hands.
PlayerClass = {}
