---@class DHTMLControls : Panel
---@field AddressBar DTextEntry
---@field BackButton DImageButton
---@field ForwardButton DImageButton
---@field RefreshButton DImageButton
---@field HomeButton DImageButton
---@field StopButton DImageButton
---@field History table<integer, string>
---@field Cur integer
---@field Navigating? boolean
---@field BorderSize number
---@field BackgroundColor Color
---@field HomeURL string
---@field HTML? DHTML
local DHTMLControls = {}
