---@class DFileBrowser : Panel
--- The horizontal divider separating the tree and file list.
---@field Divider DHorizontalDivider
--- The directory tree panel.
---@field Tree DTree
--- The file list panel showing files in the current folder.
---@field Files DListView
--- The current path search string.
---@field m_strSearch string
--- The base folder path to browse from.
---@field m_strBaseFolder string
--- The current folder path being viewed.
---@field m_strCurrentFolder string
--- The file extension filter string.
---@field m_strFilter string
--- The virtual file path root (e.g. "GAME", "DATA").
---@field m_strPath string
--- The display name of this file browser.
---@field m_strName string
--- Whether to show models instead of files.
---@field m_bModels boolean
--- Whether the browser is currently expanded/open.
---@field m_bOpen boolean
local DFileBrowser = {}
