---@class DVScrollBar : Panel
--- The up scroll button.
---@field btnUp DButton
--- The down scroll button.
---@field btnDown DButton
--- The scroll bar grip/slider button.
---@field btnGrip DButton
--- Current scroll offset.
---@field Offset number
--- Current scroll position.
---@field Scroll number
--- Total size of the scrollable canvas.
---@field CanvasSize number
--- Size of the scrollbar grip.
---@field BarSize number
local DVScrollBar = {}

---@class DHScrollBar : Panel
--- The left scroll button.
---@field btnLeft DButton
--- The right scroll button.
---@field btnRight DButton
--- The scroll bar grip/slider button.
---@field btnGrip DButton
--- Current scroll offset.
---@field Offset number
--- Current scroll position.
---@field Scroll number
--- Total size of the scrollable canvas.
---@field CanvasSize number
--- Size of the scrollbar grip.
---@field BarSize number
--- Whether the scroll buttons are hidden.
---@field m_HideButtons boolean
local DHScrollBar = {}
