---Creates a Winch constraint.
---@realm server
---@source https://wiki.facepunch.com/gmod/constraint.Winch
---@param pl Player The player creating the constraint.
---@param ent1 Entity First entity to constrain.
---@param ent2 Entity Second entity to constrain.
---@param bone1 number PhysObj number of first entity to constrain to. (0 for non-ragdolls).
---@param bone2 number PhysObj number of second entity to constrain to. (0 for non-ragdolls).
---@param localPos1 Vector Position relative to the first physics object to constrain to.
---@param localPos2 Vector Position relative to the second physics object to constrain to.
---@param width number Width of the rope.
---@param fwd_bind number Numpad key binding for forward action.
---@param bwd_bind number Numpad key binding for backward action.
---@param fwd_speed number Speed of forward movement.
---@param bwd_speed number Speed of backward movement.
---@param material string The material of the rope.
---@param toggle boolean Toggle behavior flag.
---@param color Color The color of the rope. See Color.
---@return Entity|false|nil # The created spring constraint. Returns `false` for invalid inputs.
---@return Entity? # The created rope entity (`keyframe_rope`). Returns `nil` if no rope was created.
---@return gmod_winch_controller? # The created winch controller.
function constraint.Winch(pl, ent1, ent2, bone1, bone2, localPos1, localPos2, width, fwd_bind, bwd_bind, fwd_speed, bwd_speed, material, toggle, color) end
