---Creates Get/Set accessors for a vector or angle element NetworkVar.
---@realm shared
---@source https://wiki.facepunch.com/gmod/Entity:NetworkVarElement
---@[call_arg("gmod.network_var", "type")]
---@param type string The NetworkVar type.
---@param slot number The NetworkVar slot.
---@param element number The vector or angle element.
---@[call_arg("gmod.network_var", "define")]
---@param name string Name of the variable, used for generated Get/Set accessors.
---@param extended? table Extra NetworkVar information.
function Entity:NetworkVarElement(type, slot, element, name, extended) end
