---Returns a [Stateless Iterator](https://www.lua.org/pil/7.3.html) for all entities.
--- Intended for use in [Generic For-Loops](https://www.lua.org/pil/4.3.5.html).
--- See [player.Iterator](https://wiki.facepunch.com/gmod/player.Iterator) for a similar function for all players.
---
--- **NOTE**: Internally, this function uses cached values that are stored in Lua, as opposed to [ents.GetAll](https://wiki.facepunch.com/gmod/ents.GetAll), which is a C++ function.
--- Because a call operation from Lua to C++ *and* with a return back to Lua is quite costly, this function will be more efficient than [ents.GetAll](https://wiki.facepunch.com/gmod/ents.GetAll).
---@realm shared
---@source https://wiki.facepunch.com/gmod/ents.Iterator
---@return fun(tbl: any, prev: integer?): integer, Entity # The iterator function.
---@return Entity[] # Table of all existing Entity. This is a cached copy of ents.GetAll.
---@return integer # The origin index (0).
function ents.Iterator() end
