---Formats the supplied number of seconds to the specified format.
---
---When no format is supplied, this returns a FormattedTime table instead.
---@realm client
---@realm menu
---@realm server
---@source https://wiki.facepunch.com/gmod/string.FormattedTime
---@overload fun(float: number): FormattedTime
---@overload fun(float: number, format: nil): FormattedTime
---@param float number Number of seconds to format.
---@param format string The format string. If this is omitted, a FormattedTime table is returned instead.
---@return string # The formatted time string.
function string.FormattedTime(float, format) end
