---Splits the string into a table of strings, separated by the second argument.
---
--- This is an alias of [string.Explode](https://wiki.facepunch.com/gmod/string.Explode), but with flipped arguments.
---@realm shared
---@realm menu
---@source https://wiki.facepunch.com/gmod/string.Split
---@generic Sep: string, Str: string
---@param Inputstring std.ConstTpl<Str> String to split
---@param Separator std.ConstTpl<Sep> Character(s) to split with.
---@return std.Split<Sep, Str> # Split table
function string.Split(Inputstring, Separator) end
