--- Override: make `text` and `pos` optional so that incrementally-built
--- TextData tables (e.g. in gmod_tool SWEP DrawHUD) do not produce
--- missing-fields / param-type-mismatch diagnostics.
--- The real draw.Text / draw.TextShadow functions do require these values
--- to be set before calling, but they are set on the same local table
--- before each call, not at construction time.
---@class (partial) TextData
---Text to be drawn.
---@field text? string
---This holds the X and Y coordinates. Key value 1 is x, key value 2 is y.
---@field pos? table
